### ISSUE TITLE
Crash during compression of single-end reads

### ISSUE THREAD

**Issue by GuillaumeHolley** [Kingsford-Group/mince#3]
Hello!

I am trying to compress the reads of a small fastq file with Mince using the following command:

> ./mince_binaries/mince_linux -e -p 4 -l SF -1 /data/gholley/ERR430991_1.fastq -o /dev/shm/gholley/ERR430991_1.fastq `

I am using the binaries provided by the Mince website. The program crashes with this output:

> [ encode] => { }
> [ threads] => { 4 }
> [ libtype] => { SF }
> [ mates1] => { /data/gholley/ERR430991_1.fastq }
> [ output] => { /dev/shm/gholley/ERR430991_1.fastq }
> there is 0 lib
> mince_linux: /home/carlk/mince/src/Mince.cpp:575: int main(int, char**): Assertion `readLibraries.size() == 1' failed.

I have all permissions required on /data/gholley and /dev/shm/gholley. The fastq file is okay (well, I used it with a different read compressor and everything was ok). Any ideas about the problem?

Thank you for your help and time.

Guillaume

**Comment by rob-p** [comment]
Hi Guillaume,

  Can you try the following command?

`./mince_binaries/mince_linux -e -p 4 -l SF -r /data/gholley/ERR430991_1.fastq -o /dev/shm/gholley/ERR430991_1.fastq`

The difference being that I've replace `-1` with `-r`.  With the library types used by Mince, `-1` and `-2` are only used with paired end reads, while `-r` is used with unpaired reads.  Please let us know if this resolves the problem you're seeing.

**Comment by GuillaumeHolley** [comment]
Hi Rob,

my bad, it's working like a charm now :)

Thank you for the help!
